# Generated by Django 2.2.5 on 2019-11-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type1', models.CharField(max_length=128)),
                ('type2', models.CharField(max_length=128)),
                ('profession_name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': '专业信息',
                'verbose_name_plural': '专业信息',
                'ordering': ['id'],
            },
        ),
    ]
