# Generated by Django 2.2.5 on 2019-11-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_profession', '0002_profession_hot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profession_Hot',
        ),
        migrations.AddField(
            model_name='profession',
            name='profession_hot',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='profession',
            name='profession_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
