# Generated by Django 2.2.5 on 2019-11-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='re_school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=128)),
                ('school_province', models.CharField(max_length=128)),
                ('student_type', models.CharField(max_length=128)),
                ('year', models.CharField(max_length=128)),
                ('epoch', models.CharField(max_length=128)),
                ('score_avg', models.IntegerField()),
                ('score_low', models.IntegerField()),
                ('score_province', models.IntegerField()),
            ],
            options={
                'verbose_name': '专业信息',
                'verbose_name_plural': '专业信息',
                'ordering': ['id'],
            },
        ),
    ]
