# Generated by Django 2.2.5 on 2019-11-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_school', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='re_school',
        ),
    ]
