# Generated by Django 2.2.5 on 2019-11-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession_Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(max_length=256)),
                ('profession_hot', models.CharField(max_length=256)),
                ('profession_type', models.CharField(max_length=256)),
            ],
        ),
    ]
