# Generated by Django 2.2.5 on 2019-11-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0002_profession_hot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profession_Hot',
        ),
    ]
