# Generated by Django 2.2.5 on 2019-11-24 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0003_delete_profession_hot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school_info',
            old_name='school_belong',
            new_name='epoch',
        ),
        migrations.RenameField(
            model_name='school_info',
            old_name='school_type1',
            new_name='lowest_score',
        ),
        migrations.RenameField(
            model_name='school_info',
            old_name='school_type2',
            new_name='student_type',
        ),
    ]
