# Generated by Django 2.2.5 on 2019-11-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0005_one_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=256)),
                ('score', models.CharField(max_length=256)),
            ],
        ),
    ]
