# Generated by Django 2.2.5 on 2019-12-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_info', '0006_school_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='one_school',
            name='pictures',
            field=models.ImageField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
