# Generated by Django 2.2.5 on 2019-11-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=32)),
                ('province', models.CharField(choices=[('GuangDong', '广东')], default='GuangDong', max_length=64)),
                ('subject', models.CharField(choices=[('science', '理科'), ('art', '文科')], default='science', max_length=64)),
                ('score', models.IntegerField(default=0)),
                ('mbti', models.CharField(default=0, max_length=32)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'ordering': ['c_time'],
            },
        ),
    ]
