# Generated by Django 2.2.5 on 2019-11-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191118_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='province',
            field=models.CharField(choices=[('广东', '广东')], default='GuangDong', max_length=64),
        ),
    ]
